---
title: "Analiza Danych - Laboratorium 6"
author:
  name: Adrian Kowalski
  affiliation: Politechnika Krakowska
subtitle: Centralne Twierdzenie Graniczne
output:
  html_document:
    df_print: paged
---

# Centralne twierdzenie graniczne

Tytułowe twierdzenie jest jedną z absolutnych podstaw jakiejkolwiek frekwentystycznej analizy danych. Z naszego punktu widzenia najbardziej przydatna będzie wersja tzw. słaba, na rachunku prawdopodobieństwa poznacie silniejsze wersje tego twierdzenia (z warunkiem Lapunowa, warunkiem Lindeberga). 

**Twierdzenie**: Niech $\{ X_n \}$ będzie ciągiem niezależnych zmiennych losowych o tym samym rozkładzie o średniej $\mu$ i wariancji $\sigma^2$. Oznaczmy przez $F_n(x)$ dystrybuantę zmiennej $\sqrt{n}(\overline{X_n} - \mu)$, a przez $F(x)$ dystrybuantę rozkładu $\mathcal{N}(0,\sigma^2)$. Wówczas 
\[ \lim_{n \rightarrow \infty} F_n(x) = F(x), \mbox{w punktach ciągłości }F(x).  \]

Uwaga: Można również powiedzieć, że $X_n \rightarrow X$ według rozkładu.
Uwaga: Możemy również zdefiniować zmienną $\frac{\overline{X_n} - \mu}{\frac{\sigma^2}{\sqrt{n}}}$, wówczas jest ona zbieżna według rozkładu do zmiennej o rozkładzie $\mathcal{N}(0,1)$.

Z empirycznego punktu widzenia, warto zastanowić się nad pytaniem dotyczącym tego ile zmiennych wystarczy zsumować, aby rozkład sumy "przypominał" odpowiedni rozkład normalny. Oczywiście zależy to od wielu czynników. Zbieżność według rozkładu nie jest zbieżnością jednostajną. Wartości wokoło średniej zbiegają szybciej niż wartości w ogonach. Wobec tego istotnymi czynnikami wpływającymi na empiryczne tempo zbieżnośći jest skośność i kurtoza zmiennej, którą sumujemy (zauważmy, że w powyższym twierdzeniu wcale nie założyliśmy istnienia momentów rzędu wyższego niż $2$). Przeprowadzimy teraz szereg symulacji, które pomogą nam określić przybliżone tempo zbieżności.

# Ćwiczenia

1. Zbadaj zachowanie sumy dwunastu zmiennych z rozkładu $\mathcal{U}[0,1]$. Dlaczego akurat dwunastu?
2. Zbadaj zachowanie sumy różnych ilości zmiennych z rozkładu dwupunktowego. Czy te wyniki kojarzą się z uzyskanymi przez nas poprzednio?
3. Zbadaj zachowanie sumy różnych ilości zmiennych z rozkładu Cauchy'ego. Czy centralne twierdzenie graniczne aplikuje się w tym przypadku?
4. Zbadaj zachowanie sumy dwudziestu zmiennych z rozkładu normalnego. Czy potrzebne tutaj było centralne twierdzenie graniczne?
5. Zbadaj zachowanie sumy różnych ilości zmiennych z rozkładu wykładniczego. Czy daje nam to dodatkowe informacje na temat innego rozkładu?
6. Zbadaj zachowanie sumy różnych ilości zmiennych z rozkładu $\chi^2$.